### ISSUE TITLE
Metadata search condition 'Responsible party' not working for some GeoNetwork datasets

### ISSUE THREAD

**Issue by Miselius** [nls-oskari/oskari.org#7]
AH-3633
Metadata search condition 'Responsible party' is currently not working for some datasets through CSW api query to GeoNetwork instance

Example ELF showcase:
1. Geo Product Finder -> Show search options -> Responsible party
2. Select: "National geographic institute of Spain (IGN)"
3. No results are found.

**Comment by ZakarFin** [comment]
This has been fixed and will be included in the next release (1.41): https://github.com/nls-oskari/oskari-server/commit/6d235f2d814eeca95a6fe59cfe0ee48035ad481b

The empty space character needs to be replaced with a wildcard character to make it work properly: https://github.com/nls-oskari/oskari-server/commit/6d235f2d814eeca95a6fe59cfe0ee48035ad481b
